from __future__ import annotations

import yaml

from boost_ai import gitops
from boost_ai.memory import ImplementationRecord, LocalMemoryBackend, MicroSpecRef, backend_from_config

from .conftest import git


def test_sanitize_removes_ai_attribution():
    msg = ("feat(auth): add refresh token rotation\n\n- invalidate previous tokens\n\n"
           "🤖 Generated with Claude Code\nCo-Authored-By: Claude <noreply@anthropic.com>\n"
           "Generated by Codex\nAI-assisted\n")
    assert gitops.sanitize_message(msg) == "feat(auth): add refresh token rotation\n\n- invalidate previous tokens"


def test_commit_uses_user_identity_and_no_trailers(repo):
    (repo / "a.txt").write_text("a\n")
    gitops.add_all(repo)
    sha = gitops.commit(repo, "feat: add a\n\nCo-authored-by: Claude <x@y>")
    log = git(repo, "log", "-1", "--format=%an <%ae>%n%B")
    assert sha and "Test User <test@example.com>" in log
    assert "Co-authored" not in log


def test_no_push_capability():
    # Pushing is deliberately absent from the harness's git layer.
    assert not any("push" in name for name in dir(gitops))


def test_worktree_lifecycle_lands_on_the_users_branch(repo):
    path = gitops.create_worktree(repo, "T-0001")
    assert path.is_dir() and gitops.current_branch(path) == "(detached)"   # no branch of its own
    (path / "new.py").write_text("x = 1\n")
    (path / "README.md").write_text("changed\n")
    assert sorted(gitops.changed_files(path)) == ["README.md", "new.py"]
    assert "new.py (new)" in gitops.diff_stat(path)
    assert "+x = 1" in gitops.diff(path)
    gitops.add_all(path)
    sha = gitops.commit(path, "feat: x")
    assert gitops.land(repo, sha, "main") == sha                         # fast-forward: the same commit
    assert (repo / "new.py").read_text() == "x = 1\n"
    gitops.remove_worktree(repo, path)
    assert not path.exists() and git(repo, "branch", "--format=%(refname:short)").split() == ["main"]
    assert not gitops.is_dirty(repo)


def test_land_cherry_picks_when_the_branch_moved_and_never_breaks_it(repo):
    path = gitops.create_worktree(repo, "T-0001")
    (path / "a.py").write_text("a\n")
    gitops.add_all(path)
    sha = gitops.commit(path, "feat: a")
    (repo / "mine.txt").write_text("user work\n")                        # the user committed meanwhile
    git(repo, "add", "mine.txt")
    git(repo, "commit", "-qm", "chore: mine")
    landed = gitops.land(repo, sha, "main")
    assert landed != sha and git(repo, "log", "-2", "--format=%s").split("\n")[:2] == ["feat: a", "chore: mine"]
    (path / "README.md").write_text("from agent\n")                     # conflicting change
    gitops.add_all(path)
    sha2 = gitops.commit(path, "feat: readme")
    (repo / "README.md").write_text("from user\n")
    git(repo, "commit", "-qam", "docs: user readme")
    before = git(repo, "rev-parse", "HEAD")
    try:
        gitops.land(repo, sha2, "main")
        raise AssertionError("conflict expected")
    except gitops.GitError:
        pass
    assert git(repo, "rev-parse", "HEAD") == before and not gitops.is_dirty(repo)   # untouched


def _record(**kw) -> ImplementationRecord:
    base = dict(project="FASR", task_id="T-0007", task_title="Refresh token rotation",
                summary="Rotate refresh tokens on every use.", timestamp="2026-10-07T00:00:00+00:00",
                micro_specs=[MicroSpecRef("T-0007-MS01", "Rotation")], decisions=["Reuse revokes family"],
                files_changed=["src/auth/service.py"], problems=["Old tokens were not persisted"],
                architecture_notes=["Token family table"], branch="boost/T-0007", commit="8ac230f")
    return ImplementationRecord(**{**base, **kw})


async def test_local_memory_write_and_search(tmp_path):
    backend = LocalMemoryBackend(tmp_path / "memory")
    where = await backend.write_implementation(_record())
    text = open(where).read()
    meta = yaml.safe_load(text.split("---\n")[1])
    assert meta["task_id"] == "T-0007" and meta["commit"] == "8ac230f"
    assert meta["micro_specs"][0]["id"] == "T-0007-MS01"
    for heading in ("# [[T-0007]]", "Project: [[FASR]]", "[[T-0007-MS01]]", "## Decisions",
                    "## Files changed", "## Problems discovered", "## Architectural reasoning"):
        assert heading in text
    hits = await backend.search_context("refresh token persisted")
    assert hits and hits[0].title.startswith("[[T-0007]]")
    assert await backend.search_context("kubernetes") == []


def test_backend_from_config_default_is_local(tmp_path):
    assert isinstance(backend_from_config({}, tmp_path), LocalMemoryBackend)


def test_harness_files_are_not_part_of_changes(repo):
    (repo / ".boost-ai" / "state").mkdir(parents=True)
    (repo / ".boost-ai" / "config.yaml").write_text("commands: {}\n")
    assert not gitops.is_dirty(repo)
    (repo / "x.py").write_text("x\n")
    assert gitops.changed_files(repo) == ["x.py"]
    gitops.add_all(repo)
    assert git(repo, "diff", "--cached", "--name-only").split() == ["x.py"]


def test_paths_with_spaces(repo):
    (repo / "my file.txt").write_text("x\n")
    assert "my file.txt" in gitops.diff_stat(repo)
    assert "+x" in gitops.diff(repo)
